- hosts: localhost
  vars:
      secret: >-
        {{ lookup(
            'delinea.core.dsv',
            'ansible-secrets:dsv-awx-demo',
            tenant=DSV_TENANT,
            client_id=DSV_CLIENT_ID,
            client_secret=DSV_CLIENT_SECRET,
        ) }}
  tasks:
    - debug: msg='DSV tenant is {{ DSV_TENANT }}'
    - debug: msg='aws_keyid is {{ secret["data"]["aws_keyid"] }}'
    - debug: msg='aws_secret_access_key is {{ secret["data"]["aws_secret_access_key"] }}'
