- hosts: localhost
  vars:
      secret: >-
        {{ lookup(
            'delinea.core.dsv',
            'ansible-secrets:first',
            tenant=DSV_TENANT,
            client_id=DSV_CLIENT_ID,
            client_secret=DSV_CLIENT_SECRET,
        ) }}
  tasks:
    - debug: msg='DSV tenant is {{ DSV_TENANT }}'
    - debug: msg='the password is {{ secret["data"]["fundamental"] }} and {{ secret["data"]["secret"] }} and {{ secret["data"]["access_key"] }}'
